apiVersion: apps/v1
kind: Deployment                            #Deployment
metadata:
  name: test-python
spec:
  #replicas: 1 ### 3 Pods should exist at all times.
  selector:  # Pods label should be defined in ReplicaSet label selector
    matchLabels:
      app: test
  template:
    metadata:
      name: test-python
      labels:
        app: test # Atleast 1 Pod label should match with ReplicaSet Label Selector
    spec:
      containers:
      - name: test-python
        image: niyazhasan/python:166
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "400Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
